# Generated by Django 5.2.1 on 2025-06-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_recurringtransaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recurringtransaction',
            old_name='category_or_source',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='recurringtransaction',
            old_name='next_run',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='recurringtransaction',
            name='repeat',
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='last_processed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
