# Generated by Django 5.2.1 on 2025-06-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='category',
        ),
        migrations.AddField(
            model_name='transaction',
            name='label',
            field=models.CharField(default='Unknown', max_length=100, verbose_name='Source / Category'),
            preserve_default=False,
        ),
    ]
